/**
 * AUTO-GENERATED by scripts/encode-portfolio.mjs — do not edit by hand.
 * Source: portfolio.private.json (gitignored plaintext)
 * Regenerate: npm run encode:portfolio
 */

import { o } from './obfuscate'

export const codingProjects = [
  {
    id: "coding-1",
    kind: 'coding',
    name: o('PS0kKA=='),
    description: o('Nyk6Lg=='),
    achievements: [
      { built: o('MTkgIWQYbDIs'), because: o('MSkqLGVraFAgNFQ+NjY=') },
      { built: o('MTkgIWQYbDIs'), because: o('MSkqLGVraFAgNFQ+NjY=') },
      { built: o('MTkgIWQYbDIs'), because: o('MSkqLGVraFAgNFQ+NjY=') },
    ],
    screenshots: [
    o('AA8bCFVWXhgABgdJHx4GBUgVRV4cBQxTXUUfAxYRFEJdRx9DEQ=='),
    ],
  },
  {
    id: "coding-2",
    kind: 'coding',
    name: o('PS0kKA=='),
    description: o('Nyk6Lg=='),
    achievements: [
      { built: o('MTkgIWQYbDIs'), because: o('MSkqLGVraFAgNFQ+NjY=') },
      { built: o('MTkgIWQYbDIs'), because: o('MSkqLGVraFAgNFQ+NjY=') },
      { built: o('MTkgIWQYbDIs'), because: o('MSkqLGVraFAgNFQ+NjY=') },
    ],
    screenshots: [
    o('AA8bCFVWXhgABgdJHx4GBUgVRV4cBQxTXUUfAxYRFEJeRx9DEQ=='),
    ],
  },
  {
    id: "coding-3",
    kind: 'coding',
    name: o('PS0kKA=='),
    description: o('Nyk6Lg=='),
    achievements: [
      { built: o('MTkgIWQYbDIs'), because: o('MSkqLGVraFAgNFQ+NjY=') },
      { built: o('MTkgIWQYbDIs'), because: o('MSkqLGVraFAgNFQ+NjY=') },
      { built: o('MTkgIWQYbDIs'), because: o('MSkqLGVraFAgNFQ+NjY=') },
    ],
    screenshots: [
    o('AA8bCFVWXhgABgdJHx4GBUgVRV4cBQxTXUUfAxYRFEJfRx9DEQ=='),
    ],
  },
]

export const musicProjects = [
  {
    id: "music-1",
    kind: 'music',
    name: o('PS0kKA=='),
    description: o('Nyk6Lg=='),
    designChoices: [
      { choice: o('MTkgIWQYbDIs'), because: o('MSkqLGVraFAgNFQ+NjY=') },
      { choice: o('MTkgIWQYbDIs'), because: o('MSkqLGVraFAgNFQ+NjY=') },
      { choice: o('MTkgIWQYbDIs'), because: o('MSkqLGVraFAgNFQ+NjY=') },
    ],
    audioFile: o('EhkNBF8XQAUcGxdLHwAIDEgeXh8IDB8dCQMdH0E='),
  },
  {
    id: "music-2",
    kind: 'music',
    name: o('PS0kKA=='),
    description: o('Nyk6Lg=='),
    designChoices: [
      { choice: o('MTkgIWQYbDIs'), because: o('MSkqLGVraFAgNFQ+NjY=') },
      { choice: o('MTkgIWQYbDIs'), because: o('MSkqLGVraFAgNFQ+NjY=') },
      { choice: o('MTkgIWQYbDIs'), because: o('MSkqLGVraFAgNFQ+NjY=') },
    ],
    audioFile: o('EhkNBF8XQAUcGxdLHwAIDEgeXh8IDB8dCgMdH0E='),
  },
  {
    id: "music-3",
    kind: 'music',
    name: o('PS0kKA=='),
    description: o('Nyk6Lg=='),
    designChoices: [
      { choice: o('MTkgIWQYbDIs'), because: o('MSkqLGVraFAgNFQ+NjY=') },
      { choice: o('MTkgIWQYbDIs'), because: o('MSkqLGVraFAgNFQ+NjY=') },
      { choice: o('MTkgIWQYbDIs'), because: o('MSkqLGVraFAgNFQ+NjY=') },
    ],
    audioFile: o('EhkNBF8XQAUcGxdLHwAIDEgeXh8IDB8dCwMdH0E='),
  },
]
